### ISSUE TITLE
brewery#show : Error message

### ISSUE THREAD

**Issue by adcousin** [adcousin/hops#152]
C'est peut-être lié à mon local uniquement mais je le mets ici parce que je comprends pas le message d'erreur.
**NB : Je n'ai eu l'erreur que pour une seule brewery donc pas d'inquiétude pour le moment**
Je suis pas au top avec le include j'ai toujours pas compris comment ça marchait.
![Screenshot from 2020-12-08 17-41-05](https://user-images.githubusercontent.com/72085355/101515230-6a7a6200-397e-11eb-8a02-67834593606e.png)

**Comment by JPS09** [comment]
Fixed by #159
