### ISSUE TITLE
Brewery#show updates

### ISSUE THREAD

**Issue by sbriclot** [adcousin/hops#156]
Remove the city from the infos, it's displayed twice (the first one comes from the full address).

And Brewery name in the banner needs to be change, not visible with the map as background.
Or need another darker style of map.

**Comment by sbriclot** [comment]
![image](https://user-images.githubusercontent.com/70663477/101529147-77a04c80-3990-11eb-8402-7fcce55dfa6a.png)

**Comment by JPS09** [comment]
We could try recreating the map appearence of our prototype in Figma but their tools are not easy to apprehend
edit : nvm I've done it
