### ISSUE TITLE
Update navbar design

### ISSUE THREAD

**Issue by Mordhin** [adcousin/hops#164]
- [x] Fond plein blanc

### Quand on n'est pas logged
- [ ] Milieu : Logo
- [ ] Droite : Login

### Quand on est logged
- [ ] Gauche : Hamburger avec My cellar + Scan barcode + Logout
- [ ] Milieu : Logo
- [ ] Droite : Search button

**Comment by JPS09** [comment]
Maybe this one ? https://www.flaticon.com/free-icon/menu_3863022?term=beer&page=1&position=15&related_item_id=3863022
