### ISSUE TITLE
Talk about the graphical charter

### ISSUE THREAD

**Issue by JPS09** [adcousin/hops#7]

**Comment by JPS09** [comment]
- [ ] Use the green from the logo on the selections [beers, Breweries, my cellar, all]

- [ ] Main icons in green
- [ ] Others icons in white

**Comment by adcousin** [comment]
Figma v1 terminé.
Encore des ajustements du style:

- [ ] Fusionner Beer-search-home et Beer-results
- [ ] Structurer nickel le brewery-info
